from .pais import Pais
from .tipo_documento_identidad import TipoDocumentoIdentidad
from .persona_natural import PersonaNatural
from .persona_juridica import PersonaJuridica
from .cliente import Cliente
from .cliente_natural import ClienteNatural
from .cliente_juridico import ClienteJuridico
from .proveedor import Proveedor
from .proveedor_natural import ProveedorNatural
from .proveedor_juridico import ProveedorJuridico