# Generated by Django 5.2 on 2026-07-03 05:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre con el que se identifica la sucursal dentro del sistema.', max_length=60, verbose_name='Nombre de la sucursal')),
                ('direccion', models.CharField(help_text='Dirección física donde se encuentra ubicada la sucursal.', max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(help_text='Número de teléfono de contacto de la sucursal, sin espacios ni caracteres especiales.', max_length=9, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener exactamente 9 dígitos.', regex='^\\d{9}$')], verbose_name='Teléfono')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre con el que se identifica el almacén dentro del sistema.', max_length=60, verbose_name='Nombre del almacén')),
                ('tipo', models.CharField(choices=[('principal', 'Almacén principal'), ('tienda', 'Tienda')], help_text='Tipo de almacén según su función dentro de la empresa, como almacén principal o tienda.', max_length=25, verbose_name='Tipo de almacén')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(help_text='Sucursal a la que pertenece el almacén.', on_delete=django.db.models.deletion.PROTECT, related_name='almacenes', to='locaciones.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'db_table': 'almacen',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AlmacenDetalleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Cantidad disponible del producto en el almacén.', verbose_name='Cantidad')),
                ('almacen', models.ForeignKey(help_text='Almacén donde se encuentra registrado el stock del producto.', on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='locaciones.almacen', verbose_name='Almacén')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(help_text='Producto al que corresponde el stock registrado.', on_delete=django.db.models.deletion.PROTECT, related_name='almacen_detalles', to='catalogo.producto', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Almacén Detalle',
                'verbose_name_plural': 'Almacén Detalles',
                'db_table': 'almacen_detalle',
                'ordering': ['cantidad'],
                'constraints': [models.UniqueConstraint(fields=('almacen', 'producto'), name='uq_almacen_producto')],
            },
        ),
        migrations.AddConstraint(
            model_name='almacen',
            constraint=models.UniqueConstraint(fields=('sucursal', 'nombre'), name='uq_almacen_sucursal_nombre'),
        ),
    ]
