# Generated by Django 5.2 on 2026-07-03 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre que identifica la caja dentro del sistema (ej.: Caja Principal, Caja 1, Caja Tienda).', max_length=60, verbose_name='Nombre de la caja')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional con información adicional sobre la caja.', max_length=255, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('abierta', 'Caja abierta'), ('cerrada', 'Caja cerrada')], default='cerrada', help_text='Estado actual de la caja, indicando si se encuentra habilitada para registrar operaciones de venta.', max_length=20, verbose_name='Estado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'caja',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CajaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la apertura de la caja.', verbose_name='Fecha de apertura')),
                ('monto_inicial', models.DecimalField(decimal_places=2, help_text='Monto de efectivo con el que se inicia la jornada de la caja.', max_digits=12, verbose_name='Monto inicial')),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, help_text='Monto total de efectivo registrado al momento del cierre de la caja.', max_digits=12, null=True, verbose_name='Monto final')),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Fecha y hora en que se realizó el cierre de la caja.', null=True, verbose_name='Fecha de cierre')),
                ('caja', models.ForeignKey(help_text='Caja a la que pertenece la apertura y cierre registrados.', on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='caja.caja', verbose_name='Caja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Usuario responsable de la apertura y cierre de la caja.', on_delete=django.db.models.deletion.PROTECT, related_name='cajas_detalle', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Caja Detalle',
                'verbose_name_plural': 'Caja Detalles',
                'db_table': 'caja_detalle',
                'ordering': ['-fecha_apertura'],
            },
        ),
    ]
