# Generated by Django 5.2 on 2026-07-03 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajadetalle',
            name='fecha_apertura',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se realizó la apertura de la caja.', verbose_name='Fecha de apertura'),
        ),
    ]
