# Generated by Django 5.2 on 2026-07-03 22:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('locaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se registró el traslado entre almacenes.', verbose_name='Fecha del traslado')),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('incompleto', 'Incompleto')], default='incompleto', help_text='Estado actual del proceso de traslado.', max_length=20, verbose_name='Estado')),
                ('almacen_destino', models.ForeignKey(help_text='Almacén al que se trasladan los productos.', on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrada', to='locaciones.almacen', verbose_name='Almacén de destino')),
                ('almacen_origen', models.ForeignKey(help_text='Almacén desde el cual se envían los productos.', on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salida', to='locaciones.almacen', verbose_name='Almacén de origen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.OneToOneField(help_text='Movimiento de inventario asociado a este traslado.', on_delete=django.db.models.deletion.PROTECT, related_name='traslado', to='inventario.movimiento', verbose_name='Movimiento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traslado',
                'verbose_name_plural': 'Traslados',
                'db_table': 'traslado',
                'ordering': ['-fecha'],
            },
        ),
    ]
