# Generated by Django 5.2 on 2026-07-03 21:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('locaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('venta', 'Venta de productos'), ('compra', 'Compra de productos'), ('traslado', 'Traslado entre almacenes'), ('ajuste', 'Ajuste de stock')], help_text='Tipo de operación que originó el movimiento de inventario, como una venta, compra, traslado o ajuste de stock.', max_length=30, verbose_name='Tipo de movimiento')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se registró el movimiento en el sistema.', verbose_name='Fecha del movimiento')),
                ('observacion', models.TextField(blank=True, help_text='Comentario u observación adicional relacionada con el movimiento, si corresponde.', verbose_name='Observación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Usuario responsable de registrar el movimiento en el sistema.', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_anterior', models.IntegerField(help_text='Cantidad disponible del producto en el almacén antes de registrar el movimiento.', verbose_name='Stock anterior')),
                ('stock_nuevo', models.IntegerField(help_text='Cantidad disponible del producto en el almacén después de registrar el movimiento.', verbose_name='Stock nuevo')),
                ('entrada', models.PositiveIntegerField(default=0, help_text='Cantidad de unidades que ingresaron al almacén mediante el movimiento.', verbose_name='Entrada')),
                ('salida', models.PositiveIntegerField(default=0, help_text='Cantidad de unidades que salieron del almacén mediante el movimiento.', verbose_name='Salida')),
                ('almacen', models.ForeignKey(help_text='Almacén donde se produjo el movimiento del producto.', on_delete=django.db.models.deletion.PROTECT, related_name='kardex', to='locaciones.almacen', verbose_name='Almacén')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(help_text='Producto al que corresponde este registro del kárdex.', on_delete=django.db.models.deletion.PROTECT, related_name='kardex', to='catalogo.producto', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(help_text='Movimiento de inventario que originó este registro de kárdex.', on_delete=django.db.models.deletion.PROTECT, related_name='kardex', to='inventario.movimiento', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'Kárdex',
                'verbose_name_plural': 'Kárdex',
                'db_table': 'kardex',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('movimiento', 'almacen', 'producto'), name='uq_kardex_movimiento_almacen_producto')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Cantidad de unidades del producto incluidas en el movimiento.', verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario del producto registrado en el momento del movimiento.', max_digits=12, verbose_name='Precio')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado al producto dentro del movimiento.', max_digits=12, verbose_name='Descuento')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, help_text='Importe total correspondiente al producto, calculado según la cantidad, el precio unitario y el descuento aplicado.', max_digits=12, verbose_name='Subtotal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(help_text='Movimiento de inventario al que pertenece este detalle.', on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventario.movimiento', verbose_name='Movimiento')),
                ('producto', models.ForeignKey(help_text='Producto involucrado en el movimiento de inventario.', on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_detalles', to='catalogo.producto', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento Detalle',
                'verbose_name_plural': 'Movimiento Detalles',
                'db_table': 'movimiento_detalle',
                'ordering': ['cantidad'],
                'constraints': [models.UniqueConstraint(fields=('movimiento', 'producto'), name='uq_movimiento_producto')],
            },
        ),
    ]
