# Generated by Django 5.2 on 2026-07-02 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre único que identifica la categoría de los productos dentro del sistema.', max_length=50, unique=True, verbose_name='Nombre Categoría')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional que proporciona información adicional sobre la categoría y su finalidad.', max_length=255, verbose_name='Descripción Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre comercial con el que se identifica el producto dentro del sistema.', max_length=60, verbose_name='Nombre del producto')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional con información adicional sobre las características del producto.', max_length=255, verbose_name='Descripción del producto')),
                ('codigo', models.CharField(help_text='Código único utilizado para identificar el producto en el sistema (código interno, SKU o código de barras).', max_length=50, unique=True, verbose_name='Código del producto')),
                ('tamanio', models.CharField(blank=True, help_text='Tamaño o medida del producto, cuando aplique (ej.: 38, M, XL, 42).', max_length=20, verbose_name='Tamaño')),
                ('color', models.CharField(blank=True, help_text='Color principal del producto.', max_length=20, verbose_name='Color')),
                ('unidad_medida', models.CharField(choices=[('PR', 'Par'), ('M', 'Metro'), ('YD', 'Yarda'), ('SQ FT', 'Pie cuadrado'), ('U', 'Unidad'), ('PC', 'Pieza')], default='U', help_text='Unidad de medida utilizada para controlar el inventario y realizar las operaciones de compra y venta.', max_length=15, verbose_name='Unidad de medida')),
                ('precio_costo', models.DecimalField(decimal_places=2, help_text='Costo de adquisición o fabricación del producto.', max_digits=12, verbose_name='Precio de costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio al que se comercializa el producto.', max_digits=12, verbose_name='Precio de venta')),
                ('stock_minimo', models.PositiveIntegerField(default=0, help_text='Cantidad mínima permitida en inventario antes de generar una alerta de reposición.', verbose_name='Stock mínimo')),
                ('foto', models.ImageField(blank=True, help_text='Imagen representativa del producto.', null=True, upload_to='productos/', verbose_name='Imagen del producto')),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el producto.', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
    ]
