# Generated by Django 5.2 on 2026-07-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_global',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado al producto dentro del sistema.', max_digits=12, verbose_name='Descuento'),
        ),
    ]
