# Generated by Django 5.2 on 2026-07-04 01:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('personas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se registró la compra.', verbose_name='Fecha de la compra')),
                ('total', models.DecimalField(decimal_places=2, help_text='Importe total de la compra, considerando todos los productos registrados.', max_digits=12, verbose_name='Total de la compra')),
                ('estado', models.CharField(choices=[('completado', 'Compra completada'), ('incompleto', 'Compra incompleta')], default='incompleto', help_text='Estado actual del proceso de compra.', max_length=20, verbose_name='Estado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.OneToOneField(help_text='Movimiento de inventario generado por esta compra.', on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='inventario.movimiento', verbose_name='Movimiento')),
                ('proveedor', models.ForeignKey(help_text='Proveedor al que se realizó la compra.', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='personas.proveedor', verbose_name='Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
                'ordering': ['-fecha'],
            },
        ),
    ]
