# Generated by Django 5.2 on 2026-06-27 07:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sueldo', models.DecimalField(decimal_places=2, help_text='Remuneración mensual acordada con el empleado, expresada en la moneda configurada para el sistema.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sueldo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('induccion', 'Inducción'), ('prueba', 'Prueba'), ('inactivo', 'Inactivo'), ('vacaciones', 'Vacaciones'), ('licencia_sueldo', 'Licencia goce sueldo'), ('licencia_no_sueldo', 'Licencia sin goce sueldo'), ('suspendido', 'Suspendido')], help_text='Estado laboral actual del empleado dentro de la empresa.', max_length=30, verbose_name='Estado')),
                ('fecha_contratacion', models.DateTimeField(help_text='Fecha en la que el empleado inició su relación laboral con la empresa.', verbose_name='Fecha de contratación')),
                ('fecha_termino', models.DateTimeField(blank=True, help_text='Fecha de finalización de la relación laboral. Déjelo vacío si el empleado continúa laborando.', null=True, verbose_name='Fecha de termino')),
                ('direccion', models.CharField(blank=True, help_text='Dirección de residencia o domicilio actual del empleado.', max_length=255, verbose_name='Dirección del empleado')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento registrada en el documento de identidad del empleado.', null=True, verbose_name='Fecha de nacimiento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('persona_natural', models.OneToOneField(help_text='Persona natural asociada al empleado, que contiene sus datos personales y de identificación.', on_delete=django.db.models.deletion.PROTECT, related_name='empleado', to='personas.personanatural', verbose_name='Persona')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['fecha_contratacion'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='empleado',
            field=models.OneToOneField(blank=True, help_text='Empleado del sistema asociado a este usuario. Permite vincular la cuenta de acceso con la información laboral.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='usuarios.empleado', verbose_name='Empleado'),
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(help_text='Identificador único del permiso utilizado por el sistema (ej: producto.crear, venta.editar).', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener el formato modulo.accion en minúsculas (ej: producto.crear).', regex='^[a-z]+\\.[a-z]+$')], verbose_name='Código Permiso')),
                ('descripcion', models.CharField(help_text='Describe la acción o funcionalidad que habilita este permiso dentro del sistema.', max_length=255, verbose_name='Descripción Permiso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permiso',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre identificador del rol dentro del sistema (ej: administrador, vendedor, cajero).', max_length=50, unique=True, verbose_name='Nombre Rol')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('permisos', models.ManyToManyField(blank=True, help_text='Conjunto de permisos asociados a este rol que determinan las acciones que puede realizar el usuario.', related_name='roles', to='usuarios.permiso', verbose_name='Permisos asignado al rol')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, help_text='Rol asignado al usuario que define sus permisos dentro del sistema.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.rol', verbose_name='Rol'),
        ),
    ]
