# Generated by Django 5.2 on 2026-06-29 05:57

import apps.core.managers.active_user_manager
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', apps.core.managers.active_user_manager.ActiveUserManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='updated_by',
        ),
    ]
