# Generated by Django 5.2 on 2026-07-04 02:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0002_alter_cajadetalle_fecha_apertura'),
        ('inventario', '0001_initial'),
        ('personas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se registró la venta.', verbose_name='Fecha de la venta')),
                ('total', models.DecimalField(decimal_places=2, help_text='Importe total de la venta, calculado a partir de los productos registrados.', max_digits=12, verbose_name='Total de la venta')),
                ('estado', models.CharField(choices=[('completada', 'Venta completada'), ('incompleta', 'Venta incompleta')], default='incompleta', help_text='Estado actual del proceso de venta.', max_length=20, verbose_name='Estado')),
                ('caja', models.ForeignKey(help_text='Caja desde la cual se registró la venta.', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='caja.caja', verbose_name='Caja')),
                ('cliente', models.ForeignKey(help_text='Cliente al que se realizó la venta.', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='personas.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.OneToOneField(help_text='Movimiento de inventario generado por esta venta.', on_delete=django.db.models.deletion.PROTECT, related_name='venta', to='inventario.movimiento', verbose_name='Movimiento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['-fecha'],
            },
        ),
    ]
