# Generated by Django 5.2 on 2026-06-27 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('natural', 'Natural'), ('juridico', 'Jurídico'), ('varios', 'Varios')], default='natural', help_text='Define el tipo de cliente registrado en el sistema (natural, jurídico o varios), lo que determina la estructura de datos asociada.', max_length=10, verbose_name='Tipo de cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClienteJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente Jurídico',
                'verbose_name_plural': 'Clientes Jurídicos',
                'db_table': 'cliente_juridico',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClienteNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente Natural',
                'verbose_name_plural': 'Clientes Naturales',
                'db_table': 'cliente_natural',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre oficial del país.', max_length=100, verbose_name='Nombre País')),
                ('iso2', models.CharField(help_text='Código ISO de 2 letras del país (ej: PE).', max_length=2, unique=True, verbose_name='Código ISO 2')),
                ('iso3', models.CharField(help_text='Código ISO de 3 letras del país (ej: PER).', max_length=3, unique=True, verbose_name='Código ISO 3')),
                ('codigo_telefonico', models.CharField(help_text='Código telefónico internacional del país (ej: +51).', max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Formato válido: +51, +1, +593', regex='^\\+\\d{1,4}$')], verbose_name='Código Telefónico')),
                ('longitud_celular', models.PositiveSmallIntegerField(help_text='Cantidad de dígitos que debe tener un número de celular en este país.', verbose_name='Longitud del número de celular')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'pais',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ruc', models.CharField(help_text='Número de RUC registrado en SUNAT que identifica de forma única a la empresa.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número celular solo debe contener dígitos.', regex='^\\d+$')], verbose_name='Número RUC')),
                ('razon_social', models.CharField(help_text='Nombre legal de la empresa registrado ante SUNAT.', max_length=250, verbose_name='Razón Social')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspension', 'Suspensión Temporal'), ('baja_provisional', 'Baja Provisional'), ('baja_definitiva', 'Baja Definitiva'), ('baja_provisional_oficio', 'Baja Provisional de Oficio'), ('baja_definitiva_oficio', 'Baja Definitiva de Oficio')], help_text='Estado tributario actual de la empresa según SUNAT (activo, suspendido, baja, etc.).', max_length=40, verbose_name='Estado de la empresa')),
                ('direccion', models.CharField(help_text='Dirección fiscal registrada en SUNAT para efectos tributarios.', max_length=250, verbose_name='Dirección')),
                ('condicion', models.CharField(choices=[('habido', 'Habido'), ('no_habido', 'No Habido')], help_text='Condición de la empresa según SUNAT (habido o no habido en el domicilio fiscal).', max_length=20, verbose_name='Condición')),
                ('departamento', models.CharField(help_text='Departamento del domicilio fiscal registrado en SUNAT.', max_length=50, verbose_name='Departamento')),
                ('provincia', models.CharField(help_text='Provincia del domicilio fiscal registrado en SUNAT.', max_length=50, verbose_name='Provincia')),
                ('distrito', models.CharField(help_text='Distrito del domicilio fiscal registrado en SUNAT.', max_length=50, verbose_name='Distrito')),
                ('ubigeo_sunat', models.CharField(help_text='Código ubigeo oficial utilizado por SUNAT para identificar la ubicación geográfica.', max_length=10, verbose_name='Ubigeo SUNAT')),
            ],
            options={
                'verbose_name': 'Persona Juridica',
                'verbose_name_plural': 'Personas Juridicas',
                'db_table': 'persona_juridica',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombres', models.CharField(help_text='Nombres registrados en el documento de identidad (DNI, pasaporte u otro).', max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(help_text='Apellido paterno según documento de identidad oficial.', max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(help_text='Apellido materno según documento de identidad oficial.', max_length=50, verbose_name='Apellido Materno')),
                ('numero_documento', models.CharField(help_text='Número del documento de identidad según el tipo seleccionado (DNI, CE, pasaporte, etc.).', max_length=20, verbose_name='Número de Documento')),
                ('numero_celular', models.CharField(blank=True, help_text='Número de contacto móvil en formato nacional o internacional sin espacios ni símbolos.', max_length=13, validators=[django.core.validators.RegexValidator(message='El número celular solo debe contener dígitos.', regex='^\\d+$')], verbose_name='Número de Celular')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico válido para notificaciones del sistema (ventas, compras, comprobantes, etc.).', max_length=100, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Persona Natural',
                'verbose_name_plural': 'Personas Naturales',
                'db_table': 'persona_natural',
                'ordering': ['apellido_paterno'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('natural', 'Natural'), ('juridico', 'Juridico'), ('varios', 'Varios')], help_text='Define si el proveedor es una persona natural, jurídica o un proveedor genérico (varios). Esto determina qué datos adicionales se deben registrar.', max_length=10, verbose_name='Tipo de proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor Jurídico',
                'verbose_name_plural': 'Proveedores Jurídicos',
                'db_table': 'proveedor_juridico',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor Natural',
                'verbose_name_plural': 'Proveedores Naturales',
                'db_table': 'proveedor_natural',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(help_text='Código oficial del tipo de documento según SUNAT o catálogo interno (ej: 01 = DNI, 06 = RUC)', max_length=2, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre corto del tipo de documento utilizado en operaciones del sistema (clientes, proveedores, etc.)', max_length=50, verbose_name='Documento de Identidad')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional que detalla el uso o alcance del tipo de documento dentro del sistema', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Documento de Identidad',
                'verbose_name_plural': 'Tipos de Documentos de Identidad',
                'db_table': 'tipo_documento_identidad',
                'ordering': ['codigo'],
            },
        ),
    ]
