# Generated by Django 5.2 on 2026-06-27 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientejuridico',
            name='cliente',
            field=models.OneToOneField(help_text='Cliente base del sistema que actúa como entidad principal para un cliente de tipo jurídico.', on_delete=django.db.models.deletion.PROTECT, related_name='cliente_juridico', to='personas.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='clientejuridico',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientejuridico',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientenatural',
            name='cliente',
            field=models.OneToOneField(help_text='Cliente base del sistema que actúa como entidad principal para un cliente de tipo natural.', on_delete=django.db.models.deletion.PROTECT, related_name='cliente_natural', to='personas.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='clientenatural',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientenatural',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pais',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pais',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientejuridico',
            name='persona_juridica',
            field=models.OneToOneField(help_text='Información legal de la empresa cliente (RUC, razón social, estado SUNAT, dirección fiscal, etc.).', on_delete=django.db.models.deletion.PROTECT, related_name='cliente_juridico', to='personas.personajuridica', verbose_name='Persona jurídica'),
        ),
        migrations.AddField(
            model_name='personanatural',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personanatural',
            name='pais',
            field=models.ForeignKey(help_text='País de nacionalidad o procedencia de la persona natural.', on_delete=django.db.models.deletion.PROTECT, related_name='personas_naturales', to='personas.pais', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='personanatural',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientenatural',
            name='persona_natural',
            field=models.OneToOneField(help_text='Datos personales del cliente (nombres, apellidos, documento de identidad, contacto, etc.).', on_delete=django.db.models.deletion.PROTECT, related_name='cliente_natural', to='personas.personanatural', verbose_name='Persona natural'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedorjuridico',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedorjuridico',
            name='persona_juridica',
            field=models.OneToOneField(help_text='Información legal de la empresa proveedora (RUC, razón social, estado SUNAT, dirección fiscal, etc.).', on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_juridico', to='personas.personajuridica', verbose_name='Persona Jurídica'),
        ),
        migrations.AddField(
            model_name='proveedorjuridico',
            name='proveedor',
            field=models.OneToOneField(help_text='Proveedor base del sistema. Este registro representa a un proveedor de tipo jurídico dentro de las operaciones de compra.', on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_juridico', to='personas.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedorjuridico',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedornatural',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedornatural',
            name='persona_natural',
            field=models.OneToOneField(help_text='Datos personales del proveedor (DNI, nombres, apellidos, etc.) asociados a este proveedor natural.', on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_natural', to='personas.personanatural', verbose_name='Persona natural'),
        ),
        migrations.AddField(
            model_name='proveedornatural',
            name='proveedor',
            field=models.OneToOneField(help_text='Proveedor base del sistema. Este registro actúa como entidad principal para cualquier proveedor natural.', on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_natural', to='personas.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedornatural',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipodocumentoidentidad',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipodocumentoidentidad',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personanatural',
            name='tipo_documento',
            field=models.ForeignKey(help_text='Tipo de documento de identidad asociado a la persona (DNI, CE, pasaporte, etc.).', on_delete=django.db.models.deletion.PROTECT, related_name='personas_naturales', to='personas.tipodocumentoidentidad', verbose_name='Tipo de Documento'),
        ),
        migrations.AddConstraint(
            model_name='personanatural',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='unique_doc_por_tipo'),
        ),
    ]
