# Generated by Django 5.2 on 2026-07-07 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumentoidentidad',
            name='longitud',
            field=models.PositiveSmallIntegerField(default=0, help_text='Número de caracteres que debe tener el documento.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Longitud del Documento'),
        ),
        migrations.AddField(
            model_name='tipodocumentoidentidad',
            name='tipo_validacion',
            field=models.CharField(choices=[('NUMERICO', 'Numérico'), ('ALFANUMERICO', 'Alfanumérico'), ('ALFABETICO', 'Alfabético')], default='NUMERICO', help_text='Indica si el número de documento es numérico, alfanumérico o alfabético, lo cual puede afectar la validación y el formato de ingreso', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='iso2',
            field=models.CharField(help_text='Código ISO de 2 letras del país (ej: PE).', max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 2 letras mayúsculas.', regex='^[A-Z]{2}$')], verbose_name='Código ISO 2'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='iso3',
            field=models.CharField(help_text='Código ISO de 3 letras del país (ej: PER).', max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 3 letras mayúsculas.', regex='^[A-Z]{3}$')], verbose_name='Código ISO 3'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='longitud_celular',
            field=models.PositiveSmallIntegerField(help_text='Cantidad de dígitos que debe tener un número de celular en este país.', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(15)], verbose_name='Longitud del número de celular'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='ruc',
            field=models.CharField(help_text='Número de RUC registrado en SUNAT que identifica de forma única a la empresa.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe contener exactamente 11 dígitos.', regex='^\\d{11}$')], verbose_name='Número RUC'),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='numero_documento',
            field=models.CharField(help_text='Número del documento de identidad según el tipo seleccionado (DNI, CE, pasaporte, etc.).', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de documento solo puede contener letras y números.', regex='^[A-Za-z0-9]+$')], verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoidentidad',
            name='codigo',
            field=models.CharField(help_text='Código oficial del tipo de documento según SUNAT o catálogo interno (ej: 01 = DNI, 06 = RUC)', max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe contener exactamente dos dígitos.', regex='^\\d{2}$')], verbose_name='Código'),
        ),
    ]
