# Generated by Django 5.2 on 2026-06-28 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('SOFT_DELETE', 'Eliminación lógica'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Intento de inicio fallido')], help_text='Acción realizada sobre el registro.', max_length=50, verbose_name='Acción')),
                ('nombre_tabla', models.CharField(blank=True, help_text='Nombre de la tabla o modelo afectado por la acción.', max_length=100, null=True, verbose_name='Nombre de la tabla')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='Identificador del registro afectado.', null=True, verbose_name='ID del objeto')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado del registro antes de realizar la acción.', null=True, verbose_name='Datos anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado del registro después de realizar la acción.', null=True, verbose_name='Datos nuevos')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde la que se realizó la solicitud.', null=True, verbose_name='Dirección IP')),
                ('agente_usuario', models.TextField(blank=True, help_text='Información del navegador o cliente que realizó la solicitud.', null=True, verbose_name='Agente de usuario')),
                ('metadata', models.JSONField(blank=True, help_text='Información adicional relacionada con el evento de auditoría.', null=True, verbose_name='Metadatos')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que ocurrió la acción.', verbose_name='Fecha')),
                ('content_type', models.ForeignKey(blank=True, help_text='Modelo al que pertenece el registro auditado.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de contenido')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que ejecutó la acción.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'db_table': 'auditoria',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
